services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 50000:50000
      - 8081:80
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
volumes:
 jenkins_home:
