# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    expose: [3306]
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: team-member-database
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    volumes:
    - mysql-data:/var/lib/mysql
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOST=mysql
    container_name: phpmyadmin

  java-app:
    image: java-app:1.0
    ports:
      - 8082:3000
    expose: [3000]
    environment:
      DB_USER: admin
      DB_PWD: adminpass
      DB_SERVER: mysql
      DB_NAME: team-member-database
    container_name: java-app

volumes:
  mysql-data:
    driver: local
